server:
  port: 1113

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: password
    driverClassName: org.h2.Driver